### ISSUE TITLE
Suggestion: situation cannot be an implicit choice in itself

### ISSUE THREAD

**Issue by Oreolek** [idmillington/undum#46]
It's an interface oddity. If you put a situation as implicit choice of itself, you can't enter it because you are already there. So I think it's a good idea to hide the option entirely. (The alternative would be to allow re-enterings, of course)

**Comment by idmillington** [comment]
A really good point! I agree, the option should be ignored. Best to do it when the list of possible situations is compiled, I think, that way the hidden situation doesn't affect the min or max limits.
