### ISSUE TITLE
How to always show the mobile user interface

### ISSUE THREAD

**Issue by Baltasarq** [idmillington/undum#53]
In my story, there are no need for stats. Actually, I'd like to always have the mobile user interface on screen, instead of the desktop version.
I've tried everything, even modifying undum.js's isMobile function to always return true, to no avail.
I think that this could be interesting for some game that do not need stats at all.
How can I do this?

**Comment by idmillington** [comment]
You should just be able to remove the stat panel from HTML file. To force it to be always Mobile you would have to go into the undum.js code, find isMobileDevice (currently around line 56) and change it to always return true.
